[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000" 
cursor  = "#aeaeae"

# cursor = "#6489ee"
[window]
padding.x = 0
padding.y = 0
# opacity = 0.85
# blur = true
# decorations = "None" 

# [colors]
# transparent_background_colors = true 
[font]
normal = {family = "Iosevka", style = 'Regular'}
size = 9

[cursor.style] 
shape = "Block"
blinking = "Never"

