[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/ondark.toml",]

[env]
TERM = "xterm-256color"

[colors.primary]
background = "#262626"
foreground = "#ffffff"

[colors.cursor]
text = "#000000" 
cursor  = "#aeaeae"

# cursor = "#6489ee"
[window]
padding.x = 0
padding.y = 0
# opacity = 0.85
# blur = true
# decorations = "None" 

# [colors]
# transparent_background_colors = true 
[font]
normal = {family = "MesloLGLNerdFontMono", style = 'Regular'}
size = 8

[cursor.style] 
shape = "Block"
blinking = "Never"

