[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[colors.primary]
background = "#1c1c1c"
foreground = "#ffffff"

[colors.cursor]
text = "#000000" 
cursor = "#ffd75f"

[window]
padding.x = 0
padding.y = 0
# opacity = 0.85
# blur = true
# decorations = "None" 

# [colors]
# transparent_background_colors = true 
[font]
normal = {family = "Hack Nerd Font", style = 'Regular'}
size = 10.5

[cursor.style] 
shape = "Block"
blinking = "Always"

