[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/ondark.toml",]

[env]
TERM = "xterm-256color"

[colors.primary]
background = "#262626"
foreground = "#ffffff"

[colors.cursor]
text = "#ffffff" 
cursor = "#6489ee"

[window]
padding.x = 3
padding.y = 3
# opacity = 0.85
# blur = true
# decorations = "None" 

# [colors]
# transparent_background_colors = true 
[font]
normal = {family = "MesloLGM Nerd Font Propo", style = 'Bold'}
size = 11

[cursor.style] 
shape = "Block"
blinking = "Never"

